const TerserPlugin = require('terser-webpack-plugin');
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: {
        decoder: './ttn/decoder.js',
    },
    target: 'es5',
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'ttn', 'dist'),
        globalObject: 'ttnglobal',
    },
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env'],
                    },
                },
            },
        ],
    },
    optimization: {
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    mangle: false,
                    format: {
                        preamble: '/* This code is autogenerated.\n' +
                        'You can find the source code here https://git.it.hs-heilbronn.de/jemaier/lorawan-akdt-hw\n' +
                        'Or email the author at mpfeffer@stud.hs-heilbronn.de or gohbgl@gmail.com */\n' +
                        'ttnglobal=this;',
                    },
                },
            }),
        ],
    },
};